name: Daily X User Fetch

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 执行
  workflow_dispatch:      # 允许手动触发

jobs:
  fetch:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Run fetch script
        env:
          GET_ID_X_TOKEN: ${{ secrets.GET_ID_X_TOKEN }}
        run: bun run scripts/index.ts
        
      - name: Commit and push if changes exist
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add accounts/*.json
          git diff --staged --quiet || (git commit -m "chore: update user data [skip ci]" && git push) 